# name: hello-world
# on: workflow_dispatch
# # in a workflow we can have only one job
# jobs:
#   build:
#     # this is the agent - runners
#     runs-on: ubuntu-latest
#     steps:
#       - name: Hello World Action
#         run: echo "Hello, World!"


name: hello-world-multiple-lines
on: workflow_dispatch
# in a workflow we can have only one job
jobs:
  build:
    # this is the agent - runners
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Action
        run: |
          echo "This is line one"
          echo "This is line two"
